# Generated by Django 2.1.7 on 2019-04-04 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Freestyle_50', 'Freestyle_50'), ('Freestyle_100', 'Freestyle_100'), ('Freestyle_200', 'Freestyle_200'), ('Freestyle_400', 'Freestyle_400'), ('Freestyle_800', 'Freestyle_800'), ('Freestyle_1500', 'Freestyle_1500'), ('Backstroke_50', 'Backstroke_50'), ('Backstroke_100', 'Backstroke_100'), ('Backstroke_200', 'Backstroke_200'), ('Breaststroke_50', 'Breaststroke_50'), ('Breaststroke_100', 'Breaststroke_100'), ('Breaststroke_200', 'Breaststroke_200'), ('Butterfly_50', 'Butterfly_50'), ('Butterfly_100', 'Butterfly_100'), ('Butterfly_200', 'Butterfly_200'), ('IndMedley200', 'IndMedley200'), ('IndMedley400', 'IndMedley400')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swimmer', to='core.User')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='core.Game'),
        ),
        migrations.AddField(
            model_name='competition',
            name='swimmers',
            field=models.ManyToManyField(related_name='competitions', to='core.Swimmer'),
        ),
    ]
