# Generated by Django 2.1.8 on 2019-04-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190407_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='swimmers',
        ),
        migrations.AddField(
            model_name='competition',
            name='swimmers',
            field=models.ManyToManyField(related_name='competitions', to='core.Swimmer'),
        ),
    ]
